### ISSUE TITLE
Where is .components() coming from?

### ISSUE THREAD

**Issue by nohillside** [stoeckley/AdventOfCode2020-Swift#1]
I'm using AoC to learn Swift, wonder where the `.components()` method is coming from you use to split inputs with? Swift 5.3 doesn't know about!?

Any pointers appreciated :-)

**Comment by stoeckley** [comment]
Yeah it's in Swift 5.3. Remember that Swift String is bridged with NSString.

https://developer.apple.com/documentation/foundation/nsstring/1413214-components
